"use client";
import { useEffect, useState, type ReactNode } from "react";
import { ExternalLink, RefreshCw } from "lucide-react";
import { getNewsNowStatus } from "@/lib/client";
import { NEWSNOW_URL, type NewsNowStatus } from "@/lib/newsnow";
export function NewsNowDiscovery({ navigation }: { navigation: ReactNode }) {
  const [status, setStatus] = useState<NewsNowStatus | null>(null); const [attempt, setAttempt] = useState(0); const [loaded, setLoaded] = useState(false); const [slow, setSlow] = useState(false);
  useEffect(() => { const controller = new AbortController(); if (!["localhost", "127.0.0.1", "[::1]"].includes(window.location.hostname) || window.location.protocol !== "http:") { setStatus({ available: false, message: "资讯发现目前仅支持本机访问，请在运行工作台的 Mac 上打开 http://127.0.0.1:3000/hotspots。" }); return () => controller.abort(); } async function check() { try { const result = await getNewsNowStatus(controller.signal); if (!controller.signal.aborted) setStatus(result); } catch (error) { if (!controller.signal.aborted) setStatus({ available: false, message: error instanceof Error ? error.message : "检查 NewsNow 连接失败，请重试。" }); } } void check(); const interval = window.setInterval(() => { if (document.visibilityState === "visible") void check(); }, 30000); return () => { controller.abort(); window.clearInterval(interval); }; }, [attempt]);
  useEffect(() => { if (!status?.available || loaded) return; const timer = window.setTimeout(() => setSlow(true), 15000); return () => window.clearTimeout(timer); }, [status?.available, loaded, attempt]);
  return <section className="newsnow-discovery" aria-label="NewsNow 资讯浏览"><div className="newsnow-toolbar">{navigation}<div className="newsnow-actions"><button className="btn compact icon-btn" aria-label="重新连接资讯" title="重新连接" onClick={() => { setStatus(null); setLoaded(false); setSlow(false); setAttempt(value => value + 1); }}><RefreshCw size={14} /></button><a className="btn compact icon-btn" aria-label="独立打开资讯" title="独立打开" href={NEWSNOW_URL} target="_blank" rel="noreferrer"><ExternalLink size={14} /></a></div></div>{status?.available ? <>{slow ? <p className="subtle" role="status">内嵌页面加载较慢。若内容空白，请尝试重新连接或独立打开。</p> : null}<iframe key={attempt} className="newsnow-frame" src={NEWSNOW_URL} title="NewsNow 实时资讯" onLoad={() => { setLoaded(true); setSlow(false); }} onError={() => setStatus({ available: false, message: "NewsNow 页面加载失败，请重新连接或独立打开。" })} /></> : <div className="newsnow-placeholder" aria-busy={!status}><h2>{status ? "暂时无法打开资讯发现" : "正在打开资讯发现"}</h2><p role={status ? "alert" : "status"}>{status?.message || "正在检查本机 NewsNow 服务…"}</p>{status ? <p className="subtle">已有 AI 选题仍可在上方页签查看。</p> : null}</div>}</section>;
}
