"use client";
/* eslint-disable @next/next/no-img-element -- Local image history thumbnails. */
import { useState } from "react";
import { ImagePlus, Columns2, Trash2 } from "lucide-react";
import { imageFileUrl, type ImageFile, type ImageGenerationSummary } from "@/lib/image-generation-types";
export function ImageGallery({ records, loading, selectedId, compared, onSelect, onCompare, statusFor, onDelete, onClearFailed, deleting }: { onDelete: (id: string) => void; onClearFailed: () => void; deleting: boolean; records: ImageGenerationSummary[]; loading: boolean; selectedId: string; compared: ImageFile[]; onSelect: (id: string) => void; onCompare: (image: ImageFile) => void; statusFor: (record: ImageGenerationSummary) => string }) {
  const [showAll, setShowAll] = useState(false);
  const visible = showAll ? records : records.filter((record) => record.imageCount > 0);
  return <div className="image-gallery-browser"><div className="image-gallery-filter" role="group" aria-label="图库筛选"><button className="btn small" type="button" aria-pressed={!showAll} onClick={() => setShowAll(false)}>已生成作品</button><button className="btn small" type="button" aria-pressed={showAll} onClick={() => setShowAll(true)}>全部记录</button>{showAll ? <button className="btn small" type="button" disabled={deleting} title="清理任务已失败且没有生成图片的记录；保留部分成功的作品" onClick={onClearFailed}><Trash2 size={14} />清理失败记录</button> : null}</div><section className="image-gallery" aria-label="作品图库" aria-busy={loading}>{!visible.length ? <p role="status">{loading ? "正在读取作品…" : "暂无图片，可切换全部记录查看任务。"}</p> : null}{visible.map((record) => <article className={`image-gallery-card ${selectedId === record.id ? "is-selected" : ""}`} key={record.id}>
    <button className="image-gallery-open" type="button" onClick={() => onSelect(record.id)} aria-label={`打开 ${record.title}`}>{record.thumbnail ? <img src={imageFileUrl(record.thumbnail.id)} alt={record.title} loading="lazy" /> : <span className="image-gallery-placeholder"><ImagePlus size={30} /><span>{statusFor(record)}</span></span>}</button>
    <div className="image-gallery-caption"><strong>{record.title}</strong><small>{statusFor(record)} · {record.size.replace("x", " × ")}</small><div><time dateTime={record.createdAt}>{new Date(record.createdAt).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })}</time><span className="image-toolbar-actions">{record.thumbnail ? <button className="btn icon small" type="button" aria-label="加入对比" title="加入对比" aria-pressed={compared.some((image) => image.id === record.thumbnail!.id)} onClick={() => onCompare(record.thumbnail!)}><Columns2 size={14} /></button> : null}<button className="btn icon small" type="button" aria-label="删除记录" title="删除记录" disabled={deleting} onClick={() => onDelete(record.id)}><Trash2 size={14} /></button></span></div></div>
  </article>)}</section></div>;
}
